- Dockerfile
https://serverfault.com/a/856593
> Allow Docker container to handle timezone DST correctly

- Makefile
The import data path should match the COURSES_ROOT setting.
> 🐛(makefile) fix import data path

- config/cms/docker_run_ci.py
- config/cms/docker_run_production.py
- config/lms/docker_run_ci.py
- config/lms/docker_run_production.py
Improve settings for deployment to Arnold
> Improve celery settings for the Hawthorn build

- config/cms/docker_build_production.py
- config/lms/docker_build_production.py
- config/lms/utils.py
Port https://github.com/openfun/fun-platform/pull/36 to Hawthorn 
I re-applied the modifications manually to the master branch where Hawthron lives.
> ♻️(build) make theme configurable in docker build

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Some settings expect other types of information than strings (boolean, dictionary, list, date, integer, etc.). When passing settings via environment variables we must specify a formatter to convert the
string to the expected type. 
This PR just adds formatters to all the settings.
> Make all settings configurable by environment variables

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Port the PR https://github.com/openfun/fun-platform/pull/45 to master
I just cherry-picked the commit to master and fixed a minor conflict due to changes in settings since the release of hawthorn.1.
> Port making all settings configurable by environment variables to master

- Dockerfile_dev
> Add editor to dev container

- config/cms/docker_run_development.py
- config/cms/docker_run_feature.py
- config/cms/docker_run_preprod.py
- config/cms/docker_run_production.py
- config/cms/docker_run_staging.py
- config/lms/docker_run_development.py
- config/lms/docker_run_feature.py
- config/lms/docker_run_preprod.py
- config/lms/docker_run_production.py
- config/lms/docker_run_staging.py
Porting fix https://github.com/openfun/openedx-docker/pull/76 to master
I cherry picked the fix commit.
> Port to master: fix logging environment in Sentry

- config/cms/docker_run_development.py
- config/cms/docker_run_feature.py
- config/cms/docker_run_preprod.py
- config/cms/docker_run_production.py
- config/cms/docker_run_staging.py
- config/lms/docker_run_development.py
- config/lms/docker_run_feature.py
- config/lms/docker_run_preprod.py
- config/lms/docker_run_production.py
- config/lms/docker_run_staging.py
Porting fix https://github.com/openfun/openedx-docker/pull/76 to hawthorn.1.
I cherry picked the fix commit.
> 🐛(sentry) fix logging environment in Sentry

- Dockerfile
- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Back port of #83 and 6245bfeb8f279583ee4de7c4b6824e3b674658d0 to `hawthorn.1`
> Configure en us locale (hawthorn.1)

- Dockerfile
- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Back port of #83 and 6245bfeb8f279583ee4de7c4b6824e3b674658d0 to `master`
> Configure en us locale (master)

- Dockerfile
- Makefile
- config/lms/docker_run_production.py
- config/lms/root_urls.py
- docker-compose.yml
- docker/files/etc/nginx/conf.d/lms.conf
- requirements.txt
Add Fonzie to add access control to instructor dashboard CSV export files, and to future edx-platform evolutions
> ✨(edxapp) add Fonzie to OEE dependencies

- .circleci/config.yml
Believe me, it's not a joke. 😥
> 👷(project) fix indentation in circle configuration

- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/requirements.txt
upgrade fonzie to its latest version which fixes an ACL bug
> ⬆️(hawthorn/1/oee) upgrade fonzie to 0.2.1

- releases/dogwood/3/bare/CHANGELOG.md
Changed:
- Add LOCALE_PATHS to configurable settings
> 🔖(dogwood/3/bare) bump to dogwood.3-1.1.0

- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
Recent changes in LMS production settings concerning the `LOCALE_PATHS setting` override are inefficient.
> 🐛(master|hawthorn/1/*) fix LOCALE_PATHS override

- .circleci/config.yml
- Makefile
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/bare/activate
- releases/eucalyptus/3/bare/config/cms/docker_build.py
- releases/eucalyptus/3/bare/config/cms/docker_build_development.py
- releases/eucalyptus/3/bare/config/cms/docker_build_production.py
- releases/eucalyptus/3/bare/config/cms/docker_run.py
- releases/eucalyptus/3/bare/config/cms/docker_run_development.py
- releases/eucalyptus/3/bare/config/cms/docker_run_preprod.py
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/cms/docker_run_staging.py
- releases/eucalyptus/3/bare/config/lms/docker_build.py
- releases/eucalyptus/3/bare/config/lms/docker_build_development.py
- releases/eucalyptus/3/bare/config/lms/docker_build_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run.py
- releases/eucalyptus/3/bare/config/lms/docker_run_development.py
- releases/eucalyptus/3/bare/config/lms/docker_run_preprod.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_staging.py
- releases/eucalyptus/3/bare/config/lms/utils.py
- releases/eucalyptus/3/bare/entrypoint.sh
Our white brands are still running OpenEdx eucalyptus release, thus we needed to build this rather old release at least for development purpose.
Configurations have been derived from our `dogwood/3/bare` settings according to this diff [1] with the focus on `lms/envs/aws.py` [2] and `cms/envs/aws.py` [3].
[1] https://github.com/edx/edx-platform/compare/named-release/dogwood.3...open-release/eucalyptus.3
[2] https://github.com/edx/edx-platform/compare/named-release/dogwood.3...open-release/eucalyptus.3diff-8a23909bc8d201fba8525b1dd6396247
[3] https://github.com/edx/edx-platform/compare/named-release/dogwood.3...open-release/eucalyptus.3diff-cbc3788a38ba3e6fde20918d40c23be9
> Add eucalyptus/3/bare release

- .circleci/config.yml
- Makefile
- docker-compose.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/activate
- releases/dogwood/3/fun/config/cms/docker_build.py
- releases/dogwood/3/fun/config/cms/docker_build_development.py
- releases/dogwood/3/fun/config/cms/docker_build_production.py
- releases/dogwood/3/fun/config/cms/docker_run.py
- releases/dogwood/3/fun/config/cms/docker_run_development.py
- releases/dogwood/3/fun/config/cms/docker_run_preprod.py
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/cms/docker_run_staging.py
- releases/dogwood/3/fun/config/cms/fun.py
- releases/dogwood/3/fun/config/lms/docker_build.py
- releases/dogwood/3/fun/config/lms/docker_build_development.py
- releases/dogwood/3/fun/config/lms/docker_build_production.py
- releases/dogwood/3/fun/config/lms/docker_run.py
- releases/dogwood/3/fun/config/lms/docker_run_development.py
- releases/dogwood/3/fun/config/lms/docker_run_preprod.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_staging.py
- releases/dogwood/3/fun/config/lms/fun.py
- releases/dogwood/3/fun/config/lms/utils.py
- releases/dogwood/3/fun/entrypoint.sh
- releases/dogwood/3/fun/requirements.txt
We need to generate a Docker image as close as possible to the current fun-mooc.fr production's VM.
> Add dogwood.3 release with fun-apps

- releases/dogwood/3/fun/CHANGELOG.md
Added:
- FUN production settings carefully splited between python and yaml files
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.1.0

- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
Despite what we expect, the default static files storage works fine, there is no need to override it.
> Rollback Eucalyptus static files backend

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
Changed:
- Upgraded `libcast-xblock` to 0.6.1
> 🔖(eucalyptus/3/wb) bump to eucalyptus.3-wb-1.7.4

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
Release notes:
https://github.com/openfun/fun-apps/releases/tag/v2.4.0+wb
> ⬆️(eucalyptus/3/wb) upgrade fun-apps to 2.4.0+wb

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
Release notes:
https://github.com/openfun/fun-apps/releases/tag/v2.4.1+wb
> ⬆️(eucalyptus/3/wb) upgrade fun-apps to 2.4.1+wb

- releases/eucalyptus/3/wb/CHANGELOG.md
Changed:
- Set basic authentification backend for development environment
- Upgrade `fun-apps` to `2.4.1+wb` to fix email report recipient bug
> 🔖(eucalyptus/3/wb) bump to eucalyptus.3-wb-1.8.1

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/requirements.txt
Redis/Redis Sentinel configuration for Eucalyptus WB flavor
> Eucalyptus wb redis cache

- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/requirements.txt
Redis/Redis Sentinel configuration for Hawthorn OEE flavor
> Hawthorn oee redis cache

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
Follow up of https://github.com/openfun/fun-apps/pull/695 and https://github.com/openfun/fun-apps/pull/696 to improve teacher image for non-square geometries.
Upgrade fun-apps and make a new release for `eucalyptus/3/wb` and `dogwood/3/fun`
> Upgrade fun apps

- .circleci/config.yml
- releases/ironwood/2/oee/CHANGELOG.md
- releases/ironwood/2/oee/config/cms/docker_run_production.py
- releases/ironwood/2/oee/config/lms/docker_run_production.py
When moving to ironwood, the password policy has been revamped.
This commit update the password policy to align it with the previous settings.
> 🔧(ironwood/2/oee) update default password policy

- .circleci/config.yml
- Makefile
- docker-compose.yml
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/cms/root_urls.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/entrypoint.sh
- releases/hawthorn/1/oee/requirements.txt
- releases/ironwood/2/oee/CHANGELOG.md
- releases/ironwood/2/oee/Dockerfile
- releases/ironwood/2/oee/config/cms/docker_run_production.py
- releases/ironwood/2/oee/config/cms/root_urls.py
- releases/ironwood/2/oee/config/lms/docker_run_production.py
- releases/ironwood/2/oee/config/lms/root_urls.py
- releases/ironwood/2/oee/entrypoint.sh
- releases/ironwood/2/oee/requirements.txt
ORA2 was not functional with the filesystem backend on `hawthorn` and `ironwood`.
> [hawthorn][ironwood] Fix ora2 filesystem bug

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/settings.yml
Added
- Add new `PLATFORM_RICHIE_URL` setting in lms config used by fun-apps
Changed
- Enable CORS requests
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.17.0

- .circleci/config.yml
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/requirements.txt
- Upgrade `fun-apps` to 2.5.0+wb for protection against VideoFront downtimes
> Upgrade eucalyptus.3 wb to fun apps 2.5.0+wb

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
There was a typo in the release history
Also reword a comment within requirements to enforce circleci to run jobs to build package.
> 📝(dogwood.3-fun) fix typo within changelog

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Upgrade `dogwood/3/fun` to fonzie v0.5.0.
> ⬆️(dogwood.3.fun) bump fonzie to 0.5.0
