openfun/openedx-docker

- Dockerfile_dev
- docker-compose.yml
We will stick to Open edX release tags, e.g. `ginkgo.1`, for `fun-platform-edxapp` container tags.
A development container tag will be suffixed by `-dev`, e.g. `ginkgo.1-dev`
This PR adds default configurations to containers used for development purpose. This is useful to avoid having to copy all configuration files when its not required (_i.e._ if not overridden).
> Add default development configurations and improve container tags

- Dockerfile
- Makefile
- config/cms.env.json
- config/docker_run_cms.py
- config/docker_run_lms.py
- config/lms.env.json
- dev-volumes.yml
- docker-compose.yml
When we implemented the first Dockerfile POC, it seemed easier to copy app files in "/app" and data files in "/data" as is often seen in Dockerfiles.
We now realize that we can avoid a lot of tweaks in settings and be friendlier to the Open edX community by sticking to the paths they use in their traditional installation procedure ("/edx/app" and "/edx/var").
Change all paths to revert to Open edX practice.
> 👩‍🏭(paths): revert to same paths as Open edX for installation

- .circleci/config.yml
- Dockerfile_dev
NB: The build-dev job depends on the build job to speed up build time by using production container cache.
> ci(circle) add build & build-dev jobs

- .circleci/config.yml
- Dockerfile_dev
* remove the useless docker built images save/load/cache pattern that is no longer required with the following configuration for a job:
```yaml
machine:
docker_layer_caching: true
```
* fix development container base image to edxapp:latest to ensure it is build on top of the latest build of the production container
>  ci(circle) remove useless containers caching

- docker-compose.yml
Avoid hard coded tags such as `ginkgo.1` in docker-compose services image name.
Fix #9
> fix(docker) make docker-compose image tags generic

- .circleci/config.yml
We do not want to push PR builds to DockerHub, this fix improves the situation by restricting the push job to the master branch.
> ci(circle) restrict hub job to the master branch

- config/lms/utils.py
We need to make settings override via YAML files more generic.
Expected configurations files names to override settings are now:
* `settings.yml` (prev. `settings.yaml`) as the `.yml` extension is more
oftlenly used than `.yaml`.
* `secrets.yml` (prev. `credentials.vault.yml`) as we try to make
the generation of this file independent from ansible (vault).
I've also slightly fixed docstrings/comments formatting (black style) :wink:
> 🚚(config) rename custom configuration files

- config/lms/utils.py
This patch fixes a bug introduced by my latest PR (see #23). We expect a
secrets.yml file.
> 🐛(settings) fix sensitive credentials file name

- Dockerfile
- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
- requirements/features.txt
After having tested recent work related to celery configuration, we needed to make minor adjustments to make celery workers functional.
> Make Celery workers great again

- config/cms/docker_build_development.py
- config/cms/docker_build_production.py
- config/cms/docker_run_ci.py
- config/cms/docker_run_development.py
- config/cms/docker_run_production.py
- config/lms/docker_build_development.py
- config/lms/docker_build_production.py
- config/lms/docker_run_ci.py
- config/lms/docker_run_development.py
- config/lms/docker_run_production.py
- config/lms/utils.py
After having tested recent work related to celery configuration, we needed to make minor adjustments to make celery workers functional when running in a container context (using OpenShift).
> Configure Celery to only accept json-serialized messages

- Dockerfile
- config/cms/docker_build_development.py
- config/cms/docker_build_production.py
- config/lms/docker_build_development.py
- config/lms/docker_build_production.py
- config/lms/utils.py
We want to be able to set a custom theme when building the Docker image in an OpenShift buildconfig. Since the config volumes are not mounted in buildconfigs, we propose to allow setting it via an environment variable.
Note: I also moved the docker_build.py file to /lms and /cms so that it works the same as in Hawthorn and we can do the same thing in Arnold to deploy...
> Make theme configurable in docker build

- config/cms/docker_build_production.py
- config/cms/docker_run_production.py
- config/lms/docker_build_production.py
- config/lms/docker_run_production.py
There is no obvious reason to store `webpack-stats.json` files in the `STATIC_ROOT` tree. It causes more problem than it solves as we need to manually copy it during deployment since it is not collected via collectstatics.
> 🐛(statics) remove webpack stats from STATIC_ROOT

- config/cms/docker_build_production.py
- config/cms/docker_run_production.py
- config/lms/docker_build_production.py
- config/lms/docker_run_production.py
**Backport of #38 for `hawthorn.1`**
There is no obvious reason to store `webpack-stats.json` files in the `STATIC_ROOT` tree. It causes more problem than it solves as we need to manually copy it during deployment since it is not collected via collectstatics.
> [hawthorn.1] 🐛(statics) remove webpack stats from STATIC_ROOT

- config/cms/docker_build_production.py
- config/cms/docker_run_production.py
- config/lms/docker_build_production.py
- config/lms/docker_run_production.py
**This PR is a backport of #41 for `master`**
In fact, changing django settings is not sufficient to change the `webpack-stats.json` path. We also need to update front-end settings that enforce the usage of the  èSTATIC_ROOT` directory as the target path to generate it (see https://github.com/edx/edx-platform/blob/master/webpack.common.config.js#L94).
For now, we will wait for edx to fix it, and we will declare a new issue to let them know what problem we encountered. This PR reverts previous changes to the settings.
> ⏪(statics) revert webpack loader settings

- config/cms/docker_run_feature.py
- config/cms/docker_run_preprod.py
- config/cms/docker_run_staging.py
- config/lms/docker_run_feature.py
- config/lms/docker_run_preprod.py
- config/lms/docker_run_staging.py
`EMAIL_BACKEND` settings in some environments is broken since 766fcd8.
> 🐛(settings) fix EMAIL_BACKEND default

- Dockerfile
Node local binaries are not available in the PATH of the production image.
Instead of adding local node binaries to the path only for the development target, we've decided to make it available for each edxapp-derived targets. This will ease the later use of paver.
> ⚡️(env) add local node binaries to the path

- .circleci/config.yml
- README.md
The name `fun-platform` did not reflect the substance and ambition of this project, which is to show a best practice Open edX Docker image, based purely on Open edX public releases and not necessarily for the exclusive use of FUN. 
We renamed the repository to `openedx-docker` so the README and other minor occurences of the word `fun-platform` had to be updated.
> Update the README after renaming the repository to openedx-docker

- docker-compose.yml
When working with development images, the defined entrypoint (that wraps commands execution in a python virtual environment), is not properly called and the resulting command is not executed in the virtual environment context.
I have the feeling that the commands is spawn in a new shell that does not inherit from the entrypoint's environment.
Redefining the `entrypoint` in the `docker-compose.yml` file seems to fix the issue.
> 🐛(compose) fix development entrypoint

- Dockerfile
- Makefile
- bin/clone_repositories
- config/cms/docker_run_development.py
- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
- docker-compose.yml
This PR is a part of a group of changes to `edx-platform`, `fun-platform` and a new repository
`configurable-lti-consumer` which aims to allow CMS to propose several preconfigured instances
of `lti-consumer` block
This PR propose a working demonstration configuration
> 🔧(lti consumer) sample configuration for our configurable LTI consumer

- config/cms/docker_run_development.py
- config/cms/docker_run_feature.py
- config/cms/docker_run_preprod.py
- config/cms/docker_run_production.py
- config/cms/docker_run_staging.py
- config/lms/docker_run_development.py
- config/lms/docker_run_feature.py
- config/lms/docker_run_preprod.py
- config/lms/docker_run_production.py
- config/lms/docker_run_staging.py
We are using the same DSN for all environments of a project but we need to be able to differentiate from which environment a log comes.
It would also be useful to log the release number so we can track which release has introduced/resolved a bug.
> 🔧(config) allow setting an environment in Sentry logs

- config/cms/docker_run_development.py
- config/cms/docker_run_feature.py
- config/cms/docker_run_preprod.py
- config/cms/docker_run_production.py
- config/cms/docker_run_staging.py
- config/lms/docker_run_development.py
- config/lms/docker_run_feature.py
- config/lms/docker_run_preprod.py
- config/lms/docker_run_production.py
- config/lms/docker_run_staging.py
We must backport to the hawthorn.1 branch our improvements to the Sentry configuration on master.
I just cherry picked the commits from https://github.com/openfun/openedx-docker/pull/72
> Port to hawthorn.1: Allow setting an environment and a release in Sentry logs

- Dockerfile
- requirements.txt
This requirement file was originally located in the oee fork of edx-platform in openfun/edx-platform. 
In fact, the small fork in edx-platform works normally if the configurable LTI consumer is not installed.
It means the fork is robust and we can handle dependencies in openedx-docker. It is easier and makes more sense for all the dependencies that we need to add that have nothing to do with the edx-platform fork.
> ➕(core) add a requirement file for Open edx Extended

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
- docker-compose.yml
- requirements.txt
Upgrading oee dependencies to use our configurable LTI XBlock version 1.0.0-rc.1 after a major refactoring.
> Upgrade configurable LTI xblock to v1.0.0-rc.1

- config/cms/docker_run_development.py
- config/cms/docker_run_feature.py
- config/cms/docker_run_preprod.py
- config/cms/docker_run_production.py
- config/cms/docker_run_staging.py
- config/lms/docker_run_development.py
- config/lms/docker_run_feature.py
- config/lms/docker_run_preprod.py
- config/lms/docker_run_production.py
- config/lms/docker_run_staging.py
The previous implementation was not working because the ENVIRONMENT setting was redefined after the LOGGING setting had already been set with the Sentry environment equal to "production". 
I propose to directly override the value of the environment in the LOGGING setting.
> Fix logging environment in Sentry

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
- docker-compose.yml
- requirements.txt
Redis is in our opinion the best practice to record sessions as it combines the speed of memory with a persistence layer.
> ✨(session) add redis as session backend

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Default configuration was using LocMemCache backend preventing
cache to be shared between containers.
By example, lms course plan was not invalidated when modifications
were made in studio.
We now use Memcached as default cache and LocMemcach for 'location mapping'
as recommended by edX
https://github.com/edx/edx-platform/blob/master/lms/envs/aws.py#L199
> 🔧(cache) configure Django cache

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Port to master branch
Default configuration was using LocMemCache backend preventing
cache to be shared between containers.
By example, lms course plan was not invalidated when modifications
were made in studio.
We now use Memcached as default cache and LocMemcach for 'location mapping'
as recommended by edX
https://github.com/edx/edx-platform/blob/master/lms/envs/aws.py#L199
> 🔧(cache) configure Django cache (Port to master branch)

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
Port to Hawthorn.1 branch
Default configuration was using LocMemCache backend preventing
cache to be shared between containers.
By example, lms course plan was not invalidated when modifications
were made in studio.
We now use Memcached as default cache and LocMemcach for 'location mapping'
as recommended by edX
https://github.com/edx/edx-platform/blob/master/lms/envs/aws.py#L199
> 🔧(cache) configure Django cache (Port to Hawthorn.1 branch)

- requirements.txt
We want to take advantage of the new features on the [XBlock configurable LTI consumer](https://github.com/openfun/xblock-configurable-lti-consumer/releases/tag/v1.0.0-rc.2):
This version has automatically resizable iframes depending on the content of the LTI iframe. 
It also removed the header that was useless and interferred with the LTI content.
Bump package version to 1.0.0-rc.2
> ⬆️(lti) upgrade xblock configurable lti consumer to 1.0.0-rc.2

- requirements.txt
The previous release of this package was subject to a packing bug and was therefore not up-to-date.
Bump package version to 1.0.0-rc.3
> ⬆️(lti) upgrade xblock configurable lti consumer to 1.0.0-rc.3

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
We were initializing TRACKING_IGNORE_URL_PATTERNS to None instead of a list
of url to ignore when writing tracking logs, making each requests track a
TypeError.
> 🐛(logging) fix wrong settings for tracking logs

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
`memcached` cache backend should be easily configurable via environment variables or the `settings.yml` file.
Backport from #95
> ✨(edxapp) make memcached host & port configurable

- requirements.txt
We experienced a flickering on page load with Marsha's iframe resizer. It was fixed in v1.21 of the [configurable LTI consumer XBlock](https://github.com/openfun/xblock-configurable-lti-consumer/pull/14/files).
Bump dependency to configurable_lti_consumer-xblock==1.2.1
> ⬆️(lti) upgrade xblock configurable LTI consumer to 1.2.1

- Dockerfile
It appears that lynx (an old headless web browser) is required to run html to text conversions in the platform backend:
https://github.com/edx/edx-platform/blob/master/openedx/core/lib/html_to_text.py#L15
> ➕(edxapp) add lynx dependency for html to text conversion

- config/cms/docker_run_production.py
- config/lms/docker_run_production.py
- requirements.txt
We want to upgrade to v1.2.2 of the [configurable LTI consumer XBlock](https://github.com/openfun/xblock-configurable-lti-consumer).
This version fixes a bug for LTI configurations that don't define defaults or hidden fields. It also allows to configure secrets separately so we don't need to encrypt the whole configuration.
> ⬆️(lti) upgrade xblock configurable LTI consumer to 1.2.2

- config/lms/docker_run_production.py
When tagging 2.9.0 we forgot API versioning related settings.
`rest_framework.versioning.URLPathVersioning` is required by DRF
to successfully route to Fonzie urls of form `api/v1.0/endpoint`
> 🔧(edxapp) add missing DRF setting required by Fonzie API

- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/master/bare/Dockerfile
One should not enforce a timezone in a Docker image. Instead, this should be set at the runtime depending on the host configuration or via the `TZ` environment variable for non-alpine images.
More, than that the configuration commands were buggy (or partially useless).
> 🔥(images) remove timezone configuration step

- .circleci/config.yml
The CI `hub` job seems broken and it is not triggered upon new git tag event.
From CircleCI's documentation:
> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must specify tag filters for those jobs.
> 👷(project) fix jobs filtering for tags

- .circleci/config.yml
The hub job is broken as project sources are not available during execution.
> 👷(project) add checkout step to the hub job

- .circleci/config.yml
We cannot build target images with the default docker-compose release.
> 👷(project) add docker-compose upgrade to the hub job

- Makefile
- docker-compose.yml
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/entrypoint.sh
During the latest project refactoring, we missed the LMS's instructor exported file volume and fonzie's support for development.
> 🐛(hawthorn/1/oee) restore instructor exports

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/cms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/cms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
This sets and order paths when edx finds i18n files. Overriding
this settings allow us to override edx-platform i18n strings by
redefining them in theme.
> 🔧(config) add LOCALE_PATHS to configurable settings

- releases/hawthorn/1/oee/CHANGELOG.md
Changed:
- Add LOCALE_PATHS to configurable settings
- Remove useless timezone configuration
- Remove useless development dependencies
- Upgraded Fonzie to v0.2.1
Fixed:
- Restore LMS's instructor exported files support and fonzie's integration in
development
> 🔖(hawthorn/1/oee) bump to hawthorn.1-oee-2.10.0

- releases/hawthorn/1/bare/CHANGELOG.md
Changed:
- Add LOCALE_PATHS to configurable settings
- Remove useless timezone configuration
- Remove useless development dependencies
> 🔖(hawthorn/1/bare) bump to hawthorn.1-2.7.0

- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/oee/CHANGELOG.md
- Restore LOCALE_PATHS override for the LMS
> Release hawthorn.1-2.7.1 & hawthorn.1-oee-2.10.1

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
Recent releases have no `RELEASE` setting defined. This setting is unfortunately required to make Sentry messages relevant.
> 🐛(dogwood|eucalyptus) add missing RELEASE setting

- .circleci/config.yml
When a new release has been tagged, we do not need to rebuild all releases and flavors we support. 
Only the hub job will get triggered upon tagging and it will only rebuild and publish the target release.
> ⚡️(circle) speed up new release publication

- .circleci/config.yml
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/activate
- releases/eucalyptus/3/wb/config/cms/docker_build.py
- releases/eucalyptus/3/wb/config/cms/docker_build_development.py
- releases/eucalyptus/3/wb/config/cms/docker_build_production.py
- releases/eucalyptus/3/wb/config/cms/docker_run.py
- releases/eucalyptus/3/wb/config/cms/docker_run_development.py
- releases/eucalyptus/3/wb/config/cms/docker_run_preprod.py
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/cms/docker_run_staging.py
- releases/eucalyptus/3/wb/config/cms/fun.py
- releases/eucalyptus/3/wb/config/lms/docker_build.py
- releases/eucalyptus/3/wb/config/lms/docker_build_development.py
- releases/eucalyptus/3/wb/config/lms/docker_build_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run.py
- releases/eucalyptus/3/wb/config/lms/docker_run_development.py
- releases/eucalyptus/3/wb/config/lms/docker_run_preprod.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_staging.py
- releases/eucalyptus/3/wb/config/lms/fun.py
- releases/eucalyptus/3/wb/config/lms/utils.py
- releases/eucalyptus/3/wb/entrypoint.sh
- releases/eucalyptus/3/wb/requirements.txt
We are running white brands using our OpenEdx's eucalyptus fork with a custom flavor of fun-apps. While migrating all our infrastructure to openshift, we need to build those base images.
Install and configure fun-apps in openfun edx-platform's eucalyptus fork.
> ✨(project) add eucalyptus/3/wb release

- Makefile
- README.md
- docker-compose.yml
- env.d/redis
- env.d/redis-sentinel
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/requirements.txt
On our flavors we want to use redis sentinel with celery and to store sessions. The version of celery does not support redis-sentinel.
> Add missing support to redis sentinel

- .circleci/config.yml
- bin/ci
This project's CI needs a little bit more attention to be more efficient.
> Fix CI job names and execution

- Makefile
- README.md
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
In PR fixing support for redis sentinel, a copy/pasta typo was nade in the SESSION_REDIS_PORT setting definition for all flavors supporting redis sentinel.
Also, a typo was made in the Readme file, the old variable name used to select redis service was kept instead of using the new one, `REDIS_SERVICE`.
> Fix SESSION_REDIS_PORT setting definition

- bin/ci
The `master` Git reference does not exist after a job checkout in CircleCI. Hence, we don't properly detect current branch changes.
> 🐛(circle) fix bin/ci checkpoint

- env.d/redis-sentinel
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/requirements.txt
In a first we choose to upgrade celery to the last version to be able to
connect to a redis sentinel. But in the meantime we installer the lib
celery-redis-sentinel in the others flavors and to be consistent we
choose to do the same in hawtorn.
> ♻️(hawthorn/1/oee) use celery-redis-sentinel to connect to sentinel

- env.d/redis-sentinel
There is a typo in the redis-sentinel env file. The sentinels key in the
BROKER_TRANSPORT_OPTIONS was mispelled, sentinel key was used instead of
sentinels.
> 🐛(docker) fix typo in redis-sentinel env file

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
CMS's celery worker refuses to start using the `root` user/group ID. This bug impacts all dogwood and eucalyptus releases.
> (dogwood|eucalyptus) Fix CMS CELERY_ACCEPT_CONTENT

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/settings.yml
- releases/dogwood/3/fun/config/lms/settings.yml
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/requirements.txt
Celery workers using `celery-redis-sentinel` are failing while using unpinned redis release (>3.x):
```[2019-12-10 19:46:25,952: ERROR/MainProcess] Unrecoverable error: AttributeError("'str' object has no attribute 'iteritems'",)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
self.blueprint.start(self)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
step.start(parent)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
return self.obj.start()
File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
blueprint.start(self)
File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start …
```
> Pin redis to 2.x.x

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/fun.py
- releases/dogwood/3/fun/config/lms/fun.py
Glowbl can be used via our dedicated xblock or LTI. The current production state enable both, I think we should follow.
> 🔧(dogwood/3/fun) add Glowbl xblock settings

- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
We want Redis to be the default session engine on our specific images. It was not the case on `dogwood.3-fun` and `eucalyptus.3-wb`.
We want our settings to be as clean as possible.
> Set redis as default session backend

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
Dogwood & Eucalyptus images locales are not properly configured for an ubuntu-based image.
> 🐛([dogwood|eucalyptus]/3/*) fix locales

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Python2 openssl support in Ubuntu 12.04 relies on the outdated system openssl library, leading to SSL certicate verification failures (lack of SNI support, etc.). To mitigate this issue, it is recommended to install a recent release of urllib3 that uses pyOpenSSL instead to achieve the checking step.
> Dogwood: fix SSL certificate checking errors

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/cms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/cms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
Edx code attempts to creates Memcached keys containing spaces which
is not allowed, so cache keys have to be sanitized.
Therefore default Django configuration is not suited, here we
set a `general` cache backend which is used by incorrect edx code and
provide a normalizing function.
> 🔧(*/flavors) configure `general` memcached cache backend

- releases/dogwood/3/fun/CHANGELOG.md
Added:
- Configure `general` cache backend including cache keys sanitizing function
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.3.7

- Makefile
- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
Compiled JS sources are not properly compiled and broke courses edition in the studio.
During this PR I've also:
> [Dogwood/Eucalyptus] fix PIPELINE settings

- Makefile
We recently changed the clean Makefile target to remove sources and data for a flavored release. We decided to make it interactive so that one cannot delete data by mistake.
The counterpart of this behavior is that we cannot force the removal and thus the `rm` command can fail when target files do not exist.
When using the clean target directly it is not an issue at all, but when used as a dependency if the clean target fails, the expected target cannot execute (_e.g._ bootstrap). So, to make a long story short, we ignore clean target errors by always returning a success exit code.
> 🐛(project) ensure the clean target never fails

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/cms/fun.py
- releases/dogwood/3/fun/config/cms/settings.yml
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/cms/fun.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/config/cms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/CHANGELOG.md
- releases/master/bare/config/cms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
The `LMS_ROOT_URL` setting is missing from dogwood and eucalyptus flavors settings.
This setting is required to compute absolute urls with protocol, domain and subdomains.
Add missing setting `LMS_ROOT_URL` in dogwood and eucalyptus flavors with a default value equal to the local address of the LMS as served in this project.
> Add missing setting lms root url and release fixes for dogwood and eucalyptus images

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
Some settings were using AUTH_TOKENS wrongly. Calling the `get`  dictionary method and passing a `default` kwarg.
We noticed this because the `PROFILE_IMAGE_SECRET_KEY` was set to None in our containers.
Replace `AUTH_TOKENS` by our `config` helpers and call it correctly. :santa: :gift:
> Fix wrong use of AUTH_TOKENS

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/fun.py
- releases/dogwood/3/fun/config/lms/fun.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/cms/fun.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/fun.py
The `LTI_XBLOCK_CONFIGURATIONS` and `LTI_XBLOCK_SECRETS` settings were not set properly in our "new" `dogwood.3-fun` and `eucalyptus-wb images`.
Add  `LTI_XBLOCK_CONFIGURATIONS` and `LTI_XBLOCK_SECRETS` settings that can be configured via yaml files and secrets.
While working on this PR, I noticed that we forgot removing the `selftest` app which poses security issues.
> Fix configurable LTI XBlock settings

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/cms/fun.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/fun.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
Some synchronous requests may be quite long (e.g. courses importation) leading to a gateway timeout response. We should be able to configure the WSGI server timeout to prevent unexpected failures.
During this work I've also moved the badly placed `LTI_XBLOCK_CONFIGURATIONS` setting for the `dogwood.3-fun` release (follow up of #168).
> ([dogwood|eucalyptus]/3/*) make Gunicorn timout configurable

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
We want to make ORA2 work on all flavors. Except for `dogwood.3-fun`, the default backend should be set to the filesystem but everything should be configurable via yaml configuration files.
> ♻️(flavors/*) make ORA2 configurable on all flavors

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/cms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/cms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
Apply to each flavors cache backend configuration inspired by FUN's
production instances. Memcached backends keys are duly sanitized and prefixed.
Please note that `video_subtitles` is a cache backend used by videofront, therefore only needed on FUN's old instances
> 🔧(*/flavors) configure default cache backends

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
Both FUN flavors were missing some settings to correctly show up
`videoupload` page.
This is what it looks like if you wonder :-D
> ✨([dogwood|eucalyptus]/3/[fun|wb]) activate studio's `videoupload` page

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
We want to bump the `fun-apps` dependency to its latest version in our `dogwood.3-fun` and `eucalyptus.3-wb` releases.
> Bump fun-apps to 5.2.0  in dogwood.3-fun and 2.2.0+wb in eucalyptus.3-wb

- releases/dogwood/3/fun/CHANGELOG.md
- releases/eucalyptus/3/wb/CHANGELOG.md
- Upgrade fun-apps to 5.2.0
- Add missing `fun` application templates directory to default templates directories
to activate `videoupload` templates
- Configure all cache backends as they are in FUN's production instance
- Upgrade fun-apps to 2.2.0+wb
- Make ORA2 configurable and use filesystem backend by default
- Configure all cache backends as they are in FUN's production instance
- Add missing `fun` application templates directory to default templates directories
to activate `videoupload` templates
> Release dogwood.3 fun 1.7.0 and eucalyptus.3 wb 1.5.0

- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/cms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
While debugging we understood that CMS wsgi pods can route celery
tasks to LMS workers, lms/cms basecode and settings being differents,
such task can't run on sender pod. Removed code was intended to configure
CELERY_QUEUES with other variant queues names for such cross-variant tasks.
We decided to remove it because its overly complicated and we will
handle this upstream in Arnold.
> 🔥(eucalyptus/3/*) remove settings related to cross-process queues

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
The fun-apps are interdependant. Some thumbnails are calculated for the catalog search page that we are not using in eucalyptus.3. 
We can neutralize the creation of useless thumbnails by setting desired `FUN_THUMBNAIL_OPTIONS` to nothing.
> 🐛(eucalyptus/3/wb) neutralize thumbnails creation as they are not used

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/utils.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_development.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/utils.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/utils.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/utils.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/utils.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/utils.py
- releases/master/bare/config/lms/docker_run_production.py
- releases/master/bare/config/lms/utils.py
Some required directories were missing inside volumes. It seems that edX does not ensure this by code when using these locations.
Add a check in setetings to make sure all required directories exist upon startup.
This was ported from [fun-apps](https://github.com/openfun/fun-apps/blob/0af5fab8ae6967428bb0a44568bdd84bccbbfcea/fun/envs/common.py#L238)
> 🐛(flavors/*) Ensure all required directories exists inside each volume

- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
The location declared for videofront subtitles cache did not exist which raised 500 errors when trying to access it.
> 🐛([dogwood|eucalyptus]/3/[fun|wb]) fix videofront subtitles cache

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/requirements.txt
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/hawthorn/1/oee/requirements.txt
- releases/master/bare/Dockerfile
When running in a container it is interesting to increase number of
workers and threads run by gunicorn. We found an interresting blogpost
explaining why and how to do that
https://pythonspeed.com/articles/gunicorn-in-docker/
Add environment variable in each flavors allowing to configure gunicorn with a number of workers and threads
> Gunicorn workers

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/bare/config/lms/utils.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_development.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/utils.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/config/lms/utils.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/utils.py
These checks are creating more problems than they solve because of all the commands that we run with volumes not mounted in jobs. In these cases, running the method `ensure_directories_exists` is throwing errors that are hard to solve. In conclusion, this was counterproductive and should be removed.
Remove checks on required directories in volumes (we added [a job in Arnold](https://github.com/openfun/arnold/pull/432) to take care of this).
> Remove method to ensure directories exist

- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/utils.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/utils.py
- releases/master/bare/Dockerfile
- releases/master/bare/config/lms/docker_run_production.py
- releases/master/bare/config/lms/utils.py
These checks are creating more problems than they solve because of all the commands that we run with volumes not mounted in jobs. In these cases, running the method `ensure_directories_exists` is throwing errors that are hard to solve. In conclusion, this was counterproductive and should be removed.
Remove checks on required directories in volumes (we added [a job in Arnold](https://github.com/openfun/arnold/pull/432) to take care of this).
:warning:  This was cut out of PR https://github.com/openfun/openedx-docker/pull/182 because builds on hawthorn and master were failing and we could not afford to delay dogwood and eucalyptus.
> Remove method to ensure directories exist hawthorn and master

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/activate
The "deactivate logging anonymous user id error" error is spamming our Sentry and doesn't help. This bug has been fixed in our 5.3.0 release of FUN's `edx-platform`.
> [dogwood/3/fun] fix fun edx platform release

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
Generating thumbnails in the cms was broken because the `MEDIA_ROOT` setting was not set properly in the config of the cms.
Set MEDIA_ROOT to the same value as in the lms
> Fix media root in cms and make a fix release

- .circleci/config.yml
- Makefile
- README.md
- bin/compose
- docker-compose.yml
- extras/nginx/Dockerfile
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/activate
We need a way to bundle an openedx release assets with the `nginx` image that will serve them to avoid side-effects in our deployment procedure (see the Arnold project).
Current work copy files collected in the edxapp release and replace duplicates by symlinks to save disk space and network bandwidth (up to 65%):
```
dogwood.3-1.2.1          	529MB
dogwood.3-1.2.1-slim     	198MB
eucalyptus.3-1.1.1       	573MB
eucalyptus.3-1.1.1-slim  	222MB
hawthorn.1-3.0.0         	959MB
hawthorn.1-3.0.0-slim    	320MB
hawthorn.1-oee-3.0.0     	960MB
hawthorn.1-oee-3.0.0-slim	320MB
```
*-slim images have been generated with the aforementioned optimization.
During this work, I've also:
> Add edxapp-nginx extras

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/activate
A long standing and known bug was fixed in [openfun/edx-platform](https://github.com/openfun/edx-platform/releases/tag/dogwood.3-fun-5.3.1).
Upgrade to openfun/edx-platform version dogwood.3-fun-5.3.1
:warning: The release process was refactored in openfun/edx-platform so the new tags are more explicit.
> 🐛(dogwood/3/fun) Fix known unpacking bug in xmodule

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/activate
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
This modification follows change of location of certificates files which
were previously stored in there own volume and have now been moved to
`media` volume in `certificate` directory.
Simplify constants needed to build url and use a different name for safety.
> 🔧(dogwood/3/fun) rewrite constants related to fun's PDF certificates urls

- releases/dogwood/3/fun/CHANGELOG.md
- Rewrite settings related to FUN's certificates download URLs
- Fixed known unpacking bug by upgrading to openfun/edx-platform version dogwood.3-fun-5.3.1
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.8.4

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- Certificates are in a directory with a french name: "attestations"
> Fix certificates directory name and release a fix: dogwood.3-fun-1.8.4

- releases/eucalyptus/3/wb/CHANGELOG.md
- `edx-platform` fork Git reference recently moved to `eucalyptus.3-wb`
> 🔖(eucalyptus/3/wb) bump to eucalyptus.3-wb-1.6.2

- releases/hawthorn/1/oee/CHANGELOG.md
- Generate `edxapp-nginx` companion
> 🔖(hawthorn/1/oee) bump to hawthorn.1-oee-3.1.1

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
We recently fixed a cache busting issue on fun-apps' static files:
- https://github.com/openfun/fun-apps/pull/677
- https://github.com/openfun/fun-apps/pull/678
> Upgrade fun-apps in wb + fun flavors

- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
Now that we may use `hawthorn` images without mounting a dedicated volume for static files (see the edxapp-nginx extra), the backend still requires `webpack-stats.json` files generated via the `update_assets` `paver` command.
> Fix hawthorn.1 expected webpack-stats.json files

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- Upgrade `fun-apps` to `5.3.0` to cache home page for authenticated users
> (dogwood/3/fun) Add cache to home page for authenticated users and release dogwood.3-fun-1.9.0

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/cms/docker_run_production.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/cms/docker_run_production.py
- releases/master/bare/config/lms/docker_run_production.py
We noticed the `FILE_UPLOAD_STORAGE_BUCKET_NAME` setting was not configurable anymore because it was overriden by a hardcoded value.
In parallel, the previous release was attempting to accelerate the dogwood.3-fun home page but we found out that most of the time was in fact spent in the view.
> (dogwood.3 fun) Fix ora2 bucket name, further accelerate home page and release dogwood.3-fun-1.9.1 fix

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
One of our white brands requires support for the `bokecc` video provider backend.
> Upgrade fun-apps for eucalyptus white brands

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
In order to configure bokecc video provider we have to add settings
related to this provider in the docker_run_production file
> add bokecc video provider settings

- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
Bokecc settings were added only in CMS config but we also need them in
the LMS config.
> Add bokecc video provider settings in LMS config

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/activate
It wasn't possible anymore to build dogwood images. A new version of virtualenv is incompatible with dogwood. We need to downgrade and pin it to a specific version
> Fix dogwood build

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
The `AUTHENTICATION_BACKENDS` setting default value was wrongly declared.
Pass the default value for the `AUTHENTICATION_BACKENDS` setting as a keyword argument.
> Fix third party auth settings

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/backends.py
- releases/dogwood/3/bare/config/lms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/backends.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/backends.py
- releases/eucalyptus/3/bare/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/backends.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/lms/backends.py
- releases/hawthorn/1/bare/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/lms/backends.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/master/bare/config/lms/backends.py
- releases/master/bare/config/lms/docker_run_production.py
Due to very heavy traffic during Coronavirus confinement , we found out that Open edX rate limiting authentication backend does not work properly behind a proxy. Indeed, it is using the `REMOTE_ADDR` header to determine a request's end user IP address. 
When placed behind a proxy, the actual end user IP address is found in the `X-Forwarded-For` header.
- Add a custom rate limiting authentication backend based on the X-Forwarded-For header,
- Refactor the way authentication backends are defined to make it more straightforward.
> Add rate limit backend for proxy

- releases/dogwood/3/fun/CHANGELOG.md
- Rate limiting authentication backend that works behind proxies
- Refactor the way authentication backends are configured to make it straightforward
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.10.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
On [fun-mooc.fr](https://www.fun-mooc.fr), we want to introduce a new status for courses in the catalog that are finished but still open for enrollment. They can be accessed by students even though there is no more activity and follow-up by a teacher.
We can call this new state : "browsable". 
The feature was implemented in [fun-apps v5.4.0](https://github.com/openfun/fun-apps/releases/tag/v5.4.0). This PR upgrades `openedx-docker` to this version of [fun-apps](https://github.com/openfun/fun-apps) and publishes it as a minor release.
> Dogwood.3 fun upgrade funapps to 5.4.0

- releases/eucalyptus/3/wb/CHANGELOG.md
Added:
- Rate limiting authentication backend that works behind proxies
Changed:
- Refactor the way authentication backends are configured to make it straightforward
- Upgrade `fun-apps` to `2.4.0+wb` to get rewritten management command to change
course enrollments from `audit` to `honor`. This command will be used by a cron job.
> 🔖(eucalyptus/3/wb) bump to eucalyptus.3-wb-1.8.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
We want to use Redis Sentinel to improve Django cache reliability,
here we add related dependencies and set default caches backend to Redis 
and MemLoc.
> ✨(dogwood/3/fun) add django-redis-sentinel-redux

- releases/dogwood/3/fun/CHANGELOG.md
Added
- Add `django-redis-sentinel-redux` to use make possible the use of
Redis Sentinel for Django cache
Changed
- Configure most Django cache backends to Redis
Removed
- Remove now useless Memcached settings
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.12.0

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/lms/docker_run_development.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_development.py
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/config/lms/docker_run_development.py
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/lms/docker_run_development.py
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/config/lms/docker_run_development.py
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/lms/docker_run_development.py
- releases/master/bare/config/lms/docker_run_development.py
In a previous modification we changed rate limit authentification
backend to work behind proxies and it brokes development images because
it can't work with Django development server as it does not set
HTTP_X_FORWARDED_FOR header.
> WIP 🐛(flavors/*) set basic authentification backend for dev. environments

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
In `dogwood.3-fun-1.12.0` we wrongly pined `django-redis` version to 4.8.0
to maintain `django-redis-sentinel-redux` compatible with Django 1.8
> 🐛(dogwood/3/fun) pin `django-redis` version to 4.5.0

- releases/dogwood/3/fun/CHANGELOG.md
Changed
- Set basic authentification backend for development environment
Fixed
- Pin `django-redis` to version 4.5.0
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-1.12.1

- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/oee/CHANGELOG.md
- Rate limiting authentication backend that works behind proxies
- Refactor the way authentication backends are configured to make it straightforward
- Set basic authentification backend for development environment
- Remove hardcoded FILE_UPLOAD_STORAGE_BUCKET_NAME value to make sure it is configurable
- Rate limiting authentication backend that works behind proxies
- Refactor the way authentication backends are configured to make it straightforward
- Set basic authentification backend for development environment
- Remove hardcoded FILE_UPLOAD_STORAGE_BUCKET_NAME value to make sure it is configurable
> Release hawthorn.1 oee 3.2.0

- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/fun/CHANGELOG.md
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/oee/CHANGELOG.md
- Allow serving static files via a CDN
- Rate limiting authentication backend that works behind proxies
- Collect static files in the `edxapp` image so it can run without mounting a volume
for its static files in Kubernetes
- Refactor the way authentication backends are configured to make it straightforward
- Set basic authentification backend for development environment
- Allow serving static files via a CDN
- Collect static files in the `edxapp` image so it can run without mounting a volume
for its static files in Kubernetes
- Allow serving static files via a CDN
- Rate limiting authentication backend that works behind proxies
- Collect static files in the `edxapp` image so it can run without mounting a volume
for its static files in Kubernetes
- Refactor the way authentication backends …
> Release all flavors on 14/05/2020

- Makefile
- docker-compose.yml
CI failed to publish the new releases to Docker Hub.
The nginx image tag was not set to `EDXAPP_IMAGE_TAG` and I mixed up what is the base `nginx` image and what is the result `edxapp-nginx` image.
> 👷(circleci) fix image tag in circleci hub job

- env.d/redis-sentinel
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_build_development.py
- releases/dogwood/3/fun/config/lms/docker_build_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_build_development.py
- releases/eucalyptus/3/wb/config/lms/docker_build_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/requirements.txt
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/hawthorn/1/oee/config/cms/docker_run_production.py
- releases/hawthorn/1/oee/config/lms/docker_build_development.py
- releases/hawthorn/1/oee/config/lms/docker_build_production.py
- releases/hawthorn/1/oee/config/lms/docker_run_production.py
- releases/hawthorn/1/oee/requirements.txt
We want to use redis-sentinel as a cache backend in openedx-docker (all flavors).
As documented in the README, we should be able to do it by setting `export REDIS_SERVICE=redis-sentinel`.
But it does not work, the bootstrap of the project fails because the cache settings does not take this into account.
On top of that, on `hawthorn` and `dogwood`, the installed  `django-redis` dependency is not compatible with `django-redis-sentinel-redux`.
- Dogwood
- Hawthorn
- Eucalyptus
> 🐛(all flavors) fix redis-sentinel support

- releases/hawthorn/1/oee/CHANGELOG.md
- Pin `django-redis` version to `4.5.0` to be able to use
`django-redis-sentinel-redux`.
- Adjust settings to support `REDIS_SERVICE=redis-sentinel`
> 🔖(hawthorn/1/oee) bump to hawthorn.1-oee-3.3.1

- releases/dogwood/3/fun/CHANGELOG.md
- releases/eucalyptus/3/wb/CHANGELOG.md
- Pin `django-redis` version to `4.5.0` to be able to use
`django-redis-sentinel-redux`.
- Adjust settings to support `REDIS_SERVICE=redis-sentinel`
- Pin splinter to 0.13.0 to avoid breaking change in 0.14.0
- Adjust settings to support `REDIS_SERVICE=redis-sentinel`
> 🔖 (eucalyptus + dogwood) bump versions

- bin/activate
Make our life easier.
To make our life easier, the `bin/activate` command will now auto-export the environment variable if started with a leading `.` or `source` operator like so: `. bin/activate`.
If the leading dot (or source) is omitted, then we fallback to regular behavior, printing the variables export commands to run.
(code inspired from: https://github.com/openfun/richie-site-factory/blob/master/bin/activate#L44)
> 🚸(bin) autoexport variables if source when activating

- bin/activate
In order to easily identify the history of the different release
when running the bin/activate command, a sort operation is added
to have the most recent branches first.
Adding a `sort` command enables to sort the list of release (in reverse order) to have the most recent release first (sorted by alphabetical order)
Before (unordered):
```plain
Select an available flavored release to activate:
[1] master/bare (default)
[2] dogwood/3/fun
[3] dogwood/3/bare
[4] ironwood/2/bare
[5] eucalyptus/3/wb
[6] eucalyptus/3/bare
[7] hawthorn/1/oee
[8] hawthorn/1/bare
```
After (most recent first):
```plain
Select an available flavored release to activate:
[1] master/bare (default)
[2] ironwood/2/bare
[3] hawthorn/1/oee
[4] hawthorn/1/bare
[5] eucalyptus/3/wb
[6] eucalyptus/3/bare
[7] dogwood/3/fun
[8] …
```
> 🎨(bin) sort release in reverse order for bin/activate

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
On fun-mooc.fr, we want to use the gelf format to log events.
We need the djehouty library installed on this image.
> ➕(dogwood/3/fun) add gelf support for logging

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
Recent builds of dogwood.3-fun install `django-classy-tags` 2.0.0, that is not compatible anymore with python 2.x.
Same problem with eucalyptus flavor.
> 🐛(dogwood/3/fun) pin `django-classy-tags` version to 0.8.0

- .circleci/config.yml
- bin/ci
- docker-compose.yml
During the improvement of the ci with the integration of a config.yml generator, two things were forgotten:
- `bin/ci update` should track `env.d/` and `docker/` folders to regenerate all targets if any changes
- As master/bare was moved to master/0/bare for naming convention purpose, `docker-compose.yml` must be updated because it uses master path as a fallback
> Fix docker-compose.yml and extend bin/ci update checks

- .circleci/config.yml
- README.md
Now that our richie demo site includes OpenEdX, we should point to it from here as well.
Update README with explanations and credentials concerning the demo site.
> 📝(readme) add reference to demo site in README instructions

- .circleci/config.yml
- bin/ci
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
We want to avoid 500 errors on thumbnail generation when the filesystem is down due to [fun-apps](https://github.com/openfun/fun-apps)
Upgrade to fun-apps v5.4.2 which catches such errors.
> Fix thumbnail 500 when filesystem not available and release fix dogwood.3-fun-1.14.2

- Makefile
- bin/ci
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Thumbnails are heavily queried and should be placed behind the CDN.
Upgrade to [fun-apps v5.5.0](https://github.com/openfun/fun-apps/releases/tag/v5.5.0).
> Upgrade to fun apps 5.5.0 and release dogwood.3-fun-1.15.0

- .circleci/config.yml
- Makefile
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/Dockerfile
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/Dockerfile
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/Dockerfile
- releases/ironwood/2/bare/Dockerfile
- releases/ironwood/2/oee/Dockerfile
- releases/master/0/bare/Dockerfile
In order to not mess up user filesystem, the build should not be run as a root user.
This commit add a `check-root-user` make target that will check if the user running the make is not with an id = 0 (root).
To guard any make target from being run as root, a `check-root-user` target can be called first. If the user is root, then the command will fail with a warning message. The warning/fail behavior can be override by setting a `ALLOW_ROOT` variable like: 
```
$ sudo ALLOW_ROOT=1 make bootstrap
```
Fixes https://github.com/openfun/openedx-docker/issues/204
> 🔨(project) warn user when running make bootstrap from root user

- .circleci/config.yml
- Makefile
- README.md
- bin/compose
Make bootstrap was broken for the master flavor when run as default without activating any flavor explicitly via the `bin/activate` script. This goes back to when we [moved it to master/0](https://github.com/openfun/openedx-docker/pull/245/files) to follow the same pattern as the other flavors and improve the CI.
Add `/0` to all variable default values where it is missing.
> 🐛(master) fix make bootstrap for master/0/bare

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
We want to fix the `update_courses` command that is failing badly when a course happens to have an invalid key.
Bump [fun-apps](https://github.com/openfun/fun-apps) to [5.5.1](https://github.com/openfun/fun-apps/releases/tag/v5.5.1)
> [dogwood/3/fun] Upgrade fun apps to 5.5.1 and release fix dogwood.3-fun-1.15.1

- releases/hawthorn/1/oee/CHANGELOG.md
- releases/ironwood/2/oee/CHANGELOG.md
- Make ORA2 work with the filesystem backend
- Make ORA2 work with the filesystem backend
> [hawthorn][ironwood] Release fix for ORA2 with filesystem backend

- .circleci/config.yml
- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/config/cms/docker_run_production.py
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
The `DEFAULT_COURSE_ABOUT_IMAGE_URL` setting is missing in the cms configuration of our `dogwood` images, generating 500 errors.
Add the missing setting and publish fix releases.
> Fix dogwood default course about image url for cms and publish fix releases

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
We want to enable the richie connector on the dogwood.3-fun image.
Bump fun-apps to v5.6.0 in the dogwood.3-fun image.
> Dogwood.3 fun upgrade fun apps to 5.6.0

- .circleci/config.yml
- README.md
Connecting to Richie and to OpenEdX is now done with separate accounts:
- in richie, users are here to edit CMS pages ;
- in OpenEdX, users are either students or teachers in the LMS.
Modify README to explain new credentials to the demo site.
> 📝(README) update demo credentials

- .circleci/config.yml
- .circleci/src/config.tpl
We need to allow external contributions to run the CI, but without injecting secrets in the environment for security concerns.
When the $DOCKER_USER environment variable is not set, we allow to pull Docker images anonymously from Docker Hub.
> 👷(project) allow Docker Hub anonynous mode

- .circleci/config.yml
- Makefile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
Fix building the dogwood/3/fun Docker image.
Uninstall django 1.4.22 prior to re-installing it.
Building the dogwood/3/fun Docker fails with the following error:
Step 51/51 : RUN NO_PREREQ_INSTALL=1     paver update_assets --settings=fun.docker_build_production --skip-collect
...
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 6, in <module>
from django.shortcuts import resolve_url
ImportError: cannot import name resolve_url
The root cause is unknown; what happens is that django==1.8.12 is installed on
top of django==1.4.22 and the shortcuts.py module finds itself right next to
the (obsolete) shortcuts/__init__.py module. The latter does not contain the
`resolve_url` function and causes the failure.
To resolve (pun intended) this, we explicitly …
> Fix dogwood/3/fun Docker build

- docker-compose.yml
- env.d/development
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
In [fun-apps](https://github.com/openfun/fun-apps) v5.7.0 was added the possibility to call a web hook each time a course is published, in order to synchronize its dates with a remote catalog like richie.
I had to update the development stack to work on this feature:
> Upgrade fun-apps to v5.7.0 and add settings for course run synchronization with richie

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- Upgrade fun-apps to v5.7.1 to fix course run synchronization for empty dates
> [dogwood.3-fun] upgrade fun apps to 5.7.1 and release fix

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- Upgrade fun-apps to v5.7.2 fixing course run synchronization to point to LMS
> [dogwood.3-fun] upgrade fun apps to 5.7.2 and release fix dogwood.3-fun-1.18.2

- .circleci/config.yml
- releases/dogwood/3/bare/CHANGELOG.md
- releases/dogwood/3/bare/Dockerfile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/ironwood/2/bare/CHANGELOG.md
- releases/ironwood/2/bare/Dockerfile
- releases/ironwood/2/oee/CHANGELOG.md
- releases/ironwood/2/oee/Dockerfile
- releases/master/0/bare/CHANGELOG.md
- releases/master/0/bare/Dockerfile
As python 2.7 is used in all ubuntu images, we need to get matching pip version (https://github.com/pypa/get-pip/issues/82)
Get pip from this url : https://bootstrap.pypa.io/2.7/get-pip.py
> 🐛(dockerfiles) install pip for python 2.7

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
- Upgrade to xblock-proctor-exam to 1.0.0 to fix proctoring after API change
- Fix pip install for python 2.7
- Upgrade to xblock-proctor-exam to 1.0.0 to fix proctoring after API change
- Fix pip install for python 2.7
> Upgrade xblock proctorexam to fix api change and release fixes

- .circleci/config.yml
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/config/cms/root_urls.py
- releases/hawthorn/1/oee/config/lms/root_urls.py
- releases/ironwood/2/oee/CHANGELOG.md
- releases/ironwood/2/oee/config/cms/root_urls.py
- releases/ironwood/2/oee/config/lms/root_urls.py
ORA2 urls were declared without any prefix and were matching too many url patterns, breaking (at least) assets.
- Fix ORA2 urls that were breaking assets
- Fix pip install for python 2.7
- Fix ORA2 urls that were breaking assets
- Fix pip install for python 2.7
> [hawthorn][ironwood] Fix assets broken while fixing ORA2 urls + release fixes

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
Due to python 2 compatibility, some dependencies can no longer be installed for the dogwood release, breaking our Docker image build workflow.
To mitigate the issue, we decided to update our Docker image build strategy to start from the last-usable build, update fun-specific dependencies and compile/collect static files in a new image.
> ♻️(dogwood/3/fun) refactor build strategy

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- Update Docker build strategy to start from the latest working image
> 🔖(dogwood/3/fun) bump to dogwood.3-fun-2.0.0

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Bump fun-apps to version 5.9.0 then prepare release of dogwood.3-fun 2.1.0
- Upgrade fun-apps to v5.9.0
> Dogwood/3/fun - bump fun apps to 5.9.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
Latest dogwood.3-fun build does not reflect expected changes (outdated dependencies).
The `production` stage should copy build dependencies, static files and sources from the `builder` stage.
> Fix dogwood.3-fun build

- .circleci/config.yml
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/requirements.txt
The eucalyptus builds were broken after the `get-pip.py` script moved location.
- Modify url where the `get-pip.py` script is fetched
- Install the `github.txt` requirements with a newer version of pip than the other requirements files which require an older version...
> Fix eucalyptus builds after `get-pip.py` script moved location

- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/Dockerfile
We previously upgraded `pip` to fix installing the github dependencies but it broke again. In fact, it's `setuptools`  that must be upgraded.
Replace the `pip` upgrade by a `setuptools` upgrade.
> Fix eucalyptus build by upgrading setuptools

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/requirements.txt
- Fix sources.list for Ubuntu 12.04 moved to old releases
- Broken Python development dependencies in Docker development image
- Upgrade fun-apps to v5.10.1 to stop synchronizing Elasticsearch index
> Dogwood.3 fun upgrade to fun apps 5.10.1 and release dogwood.3-fun-2.2.0

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/cms/docker_run_production.py
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
- Upgrade `fun-apps` to 2.5.0+wb for protection against VideoFront downtimes
> Upgrade dogwood.3 fun to fun apps 5.11.0 and make release

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- Update config files in DockerFile even starting from an existing image
> Update config files to recover missing videofront CDN setting and release fix

- .circleci/config.yml
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/bare/patches/edx-platform_hawthorn.1-bare_requirements-py2neo.patch
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/hawthorn/1/oee/patches/edx-platform_hawthorn.1-oee_requirements-py2neo.patch
- releases/master/0/bare/CHANGELOG.md
- releases/master/0/bare/Dockerfile
- releases/master/0/bare/patches/edx-platform_master.0-bare_requirements-py2neo.patch
Master and Hawthorn images are currently not able to build correctly for two reasons:
- path to retrieve get-pip.py for python 2.7 is outdated
- py2neo 3.1.2 is no more available from pypi
> Fix/master & hawthorn builds

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/ironwood/2/bare/CHANGELOG.md
- releases/ironwood/2/oee/CHANGELOG.md
- Set `SESSION_COOKIE_SECURE` to True by default
- Fix build by installing py2neo 3.1.2 from its github repository
- Set `SESSION_COOKIE_SECURE` to True by default
- Fix build by installing py2neo 3.1.2 from its github repository
- Fix pip install for python 2.7
- Set `SESSION_COOKIE_SECURE` to True by default
- Fix build by installing py2neo 3.1.2 from its github repository
- Fix build after get-pip.py script moved location
- Set `SESSION_COOKIE_SECURE` to True by default
- Fix build by installing py2neo 3.1.2 from its github repository
- Fix build after get-pip.py script moved location
- Fix pip install for python 2.7
- Set `SESSION_COOKIE_SECURE` to True by default
- Set `SESSION_COOKIE_SECURE` to True by default
- Fix build after get-pip.py script moved location
- Set …
> Release session cookie secure fix

- .circleci/config.yml
- .circleci/src/config.tpl
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/Dockerfile
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/Dockerfile
- releases/ironwood/2/bare/Dockerfile
- releases/ironwood/2/oee/Dockerfile
- releases/master/0/bare/Dockerfile
Since pypi banned clients that don't support SNI, we did not manage to build the image from scratch and tried to build each image on top of the previous image.
This strategy causes our images to inflate and is not sustainable.
We now propose to revert building the image from a plain  Ubuntu 12.04 image and upgrade its Python 2 to 2.7.18, the last version available which supports SNI.
Following @jbpenrath's suggestion to fix a typo, all images had to rebuild so I also added a fix of the Eucalpytus images.
> ♻️(dogwood/3/fun) revert to building the image from scratch

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/hawthorn/1/bare/CHANGELOG.md
- releases/hawthorn/1/bare/Dockerfile
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/Dockerfile
- releases/ironwood/2/bare/CHANGELOG.md
- releases/ironwood/2/bare/Dockerfile
- releases/ironwood/2/oee/CHANGELOG.md
- releases/ironwood/2/oee/Dockerfile
- releases/master/0/bare/Dockerfile
We were building our own specific image able to run as a non-root user. Since Nginx Inc is building an official unprivileged image, we should use it.
Use the following default definition for the nginx image:
- ARG NGINX_IMAGE_NAME=nginxinc/nginx-unprivileged
- ARG NGINX_IMAGE_TAG=1.20
> ♻️(all) use Nginx Inc's unprivileged image instead of our own

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/config/cms/docker_run_production.py
- releases/eucalyptus/3/wb/config/lms/docker_run_production.py
- releases/eucalyptus/3/wb/requirements.txt
We released a new version of [fun-apps](https://github.com/openfun/fun-apps) for dogwood and eucalyptus.
For eucalytus, it adds the course runs synchronization web hook that allows keeping Richie's catalog up-to-date.
For dogwood, it adds enrollment count to the course runs synchronization, updated upon each enrollment. It also adds an API endpoint for grades.
> Dogwood and eucalypsus upgrade fun apps

- .circleci/config.yml
- releases/dogwood/3/fun/Dockerfile
voluptuous 0.13.0 is not compatible with python 2.7 so we was not able to build dogwood.3-fun image.
As a workaround, we enforce installation of a lower version (0.12.2)
> 🚑️(dogwood.3-fun) enforce to install voluptuous<0.13.0

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- Install fonzie 0.3.0 next to fun-apps
> 🔖(dogwood.3-fun) bump to version 2.5.0

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/requirements.txt
- releases/hawthorn/1/oee/CHANGELOG.md
- releases/hawthorn/1/oee/requirements.txt
- releases/ironwood/2/oee/CHANGELOG.md
- releases/ironwood/2/oee/requirements.txt
Upgrade configurable_lti_consumer-xblock to version 1.4.1 on all OpenEDX releases
> Upgrade configurable_lti_consumer-xblock to version 1.4.1

- releases/dogwood/3/fun/Dockerfile
Splinter 0.17.0 is not compatible with python 2.7 so we was not able to build dogwood.3-fun image. As a workaround, we enforce installation of a lower version (0.16.0)
> 🚑️(dogwood.3-fun) enforce to install splinter<0.17.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Upgrade `dogwood.3.fun` to fonzie v0.4.0 and prepare the release of `dogwood.3.fun` 2.7.0.
> Deps/upgrade fonzie to 0.4.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/patches/edx-platform_dogwood.3-fun_strftime-1900.patch
When users key in a datetime earlier than 1900, the whole course is broken with a 500 error and nothing can be done to fix it via the UI.
This is due to a bug in Python 2 datetime.strftime and the fact that OpenEdX does not validate the dates submitted by users.
It was fixed in Eucalyptus so I propose to port the same fix to dogwood.
> Fix datetime parse for year earlier than 1900 and release a fix

- .circleci/config.yml
- releases/eucalyptus/3/bare/CHANGELOG.md
- releases/eucalyptus/3/bare/Dockerfile
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
When running npm install on `edx-ui-toolkit`, npm tries to run a command:
`/bin/usr/git ls-remote -h -t git://github.com/bessdsv/bower-installer.git`
It seems that github does not accept this syntax anymore because it still works with `ssh://git@github.com`.
Since it's not trivial to control the git commands that npm issues, we can avoid this problem by installing only the specific packet we need.
> 🐛(eucalyptus/3/wb) avoid build error when running npm install

- .circleci/config.yml
- releases/eucalyptus/3/wb/CHANGELOG.md
- releases/eucalyptus/3/wb/Dockerfile
- releases/eucalyptus/3/wb/patches/edx-platform_eucalyptus.3-remove_faulthandler.patch
- releases/eucalyptus/3/wb/requirements.txt
We need this xblock to run Jupyter. It is already installed in the `dogwood/3/fun image`.
Added Python dependency: `ipython-xblock==0.2.0`
the build was broken because the `faulthandler` packet is not available anymore for Python 2. Since this packet is only useful to run the tests, we think we can skip its installation in the production image, so I added a patch for this.
> Install ipython xblock and Release eucalyptus.3-wb-1.13.0

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
A new version of urlib3 came out which breaks compatibility with Python2. 
Pin `urlib3` dependency to its version 1.
> 📌(dogwood/3/fun) pin urlib3 to ensure python 2 compatibility

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
The new FUN logo was recently added in fun-apps but the setting pointing to it is overriden here so the new logo won't show on the site after deployment in production.
Point setting to the new FUN logo.
> 💄(dogwood/3/fun) use new FUN logo in menu

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
Upgrade fun-apps to version 5.15.0 then Bump to dogwood.3-fun-2.9.0
- Upgrade fun-apps to version 5.15.0 to add mailing_list routes to un.subscribe users from a course's mailing list
- Use new FUN logo in menu
- Pin urlib3 to v1 to ensure Python 2 compatibility
> Deps/fun apps 5.15.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Bump fun-apps to version 5.15.1 to fix the `mailing_list` app (missing template files in package published to pypi) then release dogwood.3-fun-2.9.1
- Upgrade fun-apps to version 5.15.1 to fix Manifest.in to include mailing_list
html, po and mo files
> Deps/bump fun apps 5.15.1

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/patches/edx-platform_dogwood.3-fun_moto.patch
- releases/dogwood/3/fun/requirements.txt
- Upgrade fun-apps to version 5.16.0 to add a title to the course run synchronization webhook data
- Remove dependency to missing Python package `moto` only used in tests
> Dogwood.fun.3 upgrade fun apps to v5.16.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/config/lms/docker_run_production.py
- releases/dogwood/3/fun/requirements.txt
In the fun-apps 5.17.0 we added a new middleware to fix a bug in the Oauth2 process. We must add it in the dogwood MIDDLEWARE_CLASSES settings.
> Configure dogwood with fun-apps 5.17.0 and oauth2 middleware

- .circleci/config.yml
- Makefile
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/patches/edx-platform_dogwood.3-fun_XBlock.patch
- releases/hawthorn/1/oee/Dockerfile
- releases/hawthorn/1/oee/activate
- releases/hawthorn/1/oee/patches/edx-platform_hawthorn.1-oee_moto.patch
- releases/hawthorn/1/oee/patches/edx-platform_hawthorn.1-oee_requirements-py2neo.patch
- releases/ironwood/2/oee/Dockerfile
- releases/ironwood/2/oee/activate
- releases/ironwood/2/oee/patches/edx-platform_ironwood.2-oee_moto.patch
- releases/ironwood/2/oee/patches/edx-platform_ironwood.2-oee_requirements-py2neo.patch
The build was broken as the dependency Xblock was installed through a
corrupted git repository url. Indeed, this repository has been moved in
another github organization (edx -> openedx) and the old repository url
does not redirect to the new one. So we create a patch to amend this url
with the good one.
> 🐛(dogwood.3-fun) fix build following git dependency

- .circleci/config.yml
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Upgrade dogwood.3-fun to fonzie v0.6.0.
Then release dogwood.3-fun 2.12.0
- Upgrade fonzie to v0.6.0
- Fix build by updating Xblock package repository url
> ⬆️(dogwood.3-fun) bump fonzie to 0.6.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Upgrade dogwood.3-fun to fonzie v0.7.0.
Upgrade dogwood.3-fun to fun-apps v5.18.0.
Then release dogwood.3-fun 2.13.0
- Upgrade fonzie to v0.7.0
- Upgrade fun-apps to v5.18.0
> Dogwood.3 fun/upgrade fonzie 0.7.0 fun apps 5.18.0

- .circleci/config.yml
- .circleci/src/config.tpl
- Makefile
- README.md
- bin/compose
- bin/watch
- docker-compose.yml
- env.d/redis
docker-compose command doesn't work anymore.
we need to switch to docker compose
```sh
git grep -rl docker-compose . | xargs sed -i 's/docker-compose/docker compose/g'
git grep -rl "docker compose file" . | xargs sed -i 's/docker compose file/docker-compose file/g'
git grep -rl "../docker compose.yml" . | xargs sed -i 's/docker compose.yml/docker-compose.yml/g'
git grep -rl "/docker compose" . | xargs sed -i 's/\/docker compose/\/docker-compose/g'
```
migration: 
```sh
$ docker-compose down
$ make boostrap
```
> 🔨(backend) migration docker compose

- .circleci/config.yml
- .circleci/src/config.tpl
- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Purpose
Bump fun-apps to version 5.19.0
then release minor version of Dogwood.3-fun
> ⬆️(dogwood.3-fun) bump fun-apps to version 5.19.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/Dockerfile
- releases/dogwood/3/fun/pip.conf
- releases/dogwood/3/fun/requirements.txt
Bump fun-apps to version 5.20.0
then release minor version of Dogwood.3-fun
> ⬆️(dogwood.3-fun) bump fun-apps to version 5.20.0

- releases/dogwood/3/fun/CHANGELOG.md
- releases/dogwood/3/fun/requirements.txt
Bump fun-apps to version 5.21.0 then release minor version of Dogwood.3-fun
> ⬆️(dogwood.3-fun) bump fun-apps to version 5.21.0
